version: '3.8'
services:
  postgres_db:
    image: postgres:15
    container_name: choirapp_postgres
    environment:
      - POSTGRES_USER=choirapp
      - POSTGRES_PASSWORD=choirapp
      - POSTGRES_DB=choirapp_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U choirapp -d choirapp_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
