// <auto-generated />
using System;
using ChoirApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChoirApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChoirApp.Domain.Entities.Choir", b =>
                {
                    b.Property<Guid>("ChoirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("choir_id");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<string>("ChoirName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("choir_name");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.HasKey("ChoirId");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("ChoirName")
                        .IsUnique();

                    b.ToTable("Choirs");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.ChoirInvitation", b =>
                {
                    b.Property<Guid>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<Guid>("ChoirId")
                        .HasColumnType("uuid")
                        .HasColumnName("choir_id");

                    b.Property<DateTimeOffset>("DateSent")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_sent");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("InvitationToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invitation_token");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("InvitationId");

                    b.HasIndex("ChoirId");

                    b.HasIndex("InvitationToken")
                        .IsUnique();

                    b.ToTable("ChoirInvitations");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.ChoirSongVersion", b =>
                {
                    b.Property<Guid>("ChoirSongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("choir_song_id");

                    b.Property<Guid>("ChoirId")
                        .HasColumnType("uuid")
                        .HasColumnName("choir_id");

                    b.Property<string>("EditedLyricsChordPro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("edited_lyrics_chordpro");

                    b.Property<Guid>("EditorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("editor_user_id");

                    b.Property<DateTimeOffset>("LastEditedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_edited_date");

                    b.Property<Guid>("MasterSongId")
                        .HasColumnType("uuid")
                        .HasColumnName("master_song_id");

                    b.HasKey("ChoirSongId");

                    b.HasIndex("ChoirId");

                    b.HasIndex("EditorUserId");

                    b.HasIndex("MasterSongId", "ChoirId")
                        .IsUnique();

                    b.ToTable("ChoirSongVersions");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.MasterSong", b =>
                {
                    b.Property<Guid>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("song_id");

                    b.Property<string>("Artist")
                        .HasColumnType("text")
                        .HasColumnName("artist");

                    b.Property<string>("LyricsChordPro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lyrics_chordpro");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("SongId");

                    b.ToTable("MasterSongs");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.Playlist", b =>
                {
                    b.Property<string>("PlaylistId")
                        .HasColumnType("text")
                        .HasColumnName("playlist_id");

                    b.Property<Guid>("ChoirId")
                        .HasColumnType("uuid")
                        .HasColumnName("choir_id");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("PlaylistId");

                    b.HasIndex("ChoirId");

                    b.HasIndex("PlaylistId")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.PlaylistSection", b =>
                {
                    b.Property<Guid>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<string>("PlaylistId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("playlist_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("SectionId");

                    b.HasIndex("PlaylistId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("PlaylistSections");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.PlaylistSong", b =>
                {
                    b.Property<Guid>("PlaylistSongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_song_id");

                    b.Property<bool>("IsMasterSong")
                        .HasColumnType("boolean")
                        .HasColumnName("is_master_song");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid")
                        .HasColumnName("song_id");

                    b.HasKey("PlaylistSongId");

                    b.HasIndex("SectionId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("PlaylistSongs");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.PlaylistTag", b =>
                {
                    b.Property<string>("PlaylistId")
                        .HasColumnType("text")
                        .HasColumnName("playlist_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("PlaylistId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PlaylistTags");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.PlaylistTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<Guid>("ChoirId")
                        .HasColumnType("uuid")
                        .HasColumnName("choir_id");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("TemplateId");

                    b.HasIndex("ChoirId", "Title")
                        .IsUnique();

                    b.ToTable("PlaylistTemplates");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.PlaylistTemplateSection", b =>
                {
                    b.Property<Guid>("TemplateSectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("template_section_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("TemplateSectionId");

                    b.HasIndex("TemplateId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("PlaylistTemplateSections");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.PlaylistTemplateSong", b =>
                {
                    b.Property<Guid>("TemplateSongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("template_song_id");

                    b.Property<bool>("IsMasterSong")
                        .HasColumnType("boolean")
                        .HasColumnName("is_master_song");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid")
                        .HasColumnName("song_id");

                    b.Property<Guid>("TemplateSectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_section_id");

                    b.HasKey("TemplateSongId");

                    b.HasIndex("TemplateSectionId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("PlaylistTemplateSongs");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.SongTag", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid")
                        .HasColumnName("song_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("SongId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("SongTags");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag_name");

                    b.HasKey("TagId");

                    b.HasIndex("TagName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("google_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.UserChoir", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ChoirId")
                        .HasColumnType("uuid")
                        .HasColumnName("choir_id");

                    b.HasKey("UserId", "ChoirId");

                    b.HasIndex("ChoirId");

                    b.ToTable("UserChoirs");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.Choir", b =>
                {
                    b.HasOne("ChoirApp.Domain.Entities.User", "Admin")
                        .WithMany("AdminOfChoirs")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.ChoirInvitation", b =>
                {
                    b.HasOne("ChoirApp.Domain.Entities.Choir", "Choir")
                        .WithMany()
                        .HasForeignKey("ChoirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Choir");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.ChoirSongVersion", b =>
                {
                    b.HasOne("ChoirApp.Domain.Entities.Choir", "Choir")
                        .WithMany("ChoirSongVersions")
                        .HasForeignKey("ChoirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChoirApp.Domain.Entities.User", "Editor")
                        .WithMany("EditedSongs")
                        .HasForeignKey("EditorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChoirApp.Domain.Entities.MasterSong", "MasterSong")
                        .WithMany("ChoirSongVersions")
                        .HasForeignKey("MasterSongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Choir");

                    b.Navigation("Editor");

                    b.Navigation("MasterSong");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.Playlist", b =>
                {
                    b.HasOne("ChoirApp.Domain.Entities.Choir", "Choir")
                        .WithMany("Playlists")
                        .HasForeignKey("ChoirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChoirApp.Domain.Entities.PlaylistTemplate", "PlaylistTemplate")
                        .WithMany("Playlists")
                        .HasForeignKey("TemplateId");

                    b.Navigation("Choir");

                    b.Navigation("PlaylistTemplate");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.PlaylistSection", b =>
                {
                    b.HasOne("ChoirApp.Domain.Entities.Playlist", "Playlist")
                        .WithMany("PlaylistSections")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.PlaylistSong", b =>
                {
                    b.HasOne("ChoirApp.Domain.Entities.PlaylistSection", "PlaylistSection")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaylistSection");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.PlaylistTag", b =>
                {
                    b.HasOne("ChoirApp.Domain.Entities.Playlist", "Playlist")
                        .WithMany("PlaylistTags")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChoirApp.Domain.Entities.Tag", "Tag")
                        .WithMany("PlaylistTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.PlaylistTemplate", b =>
                {
                    b.HasOne("ChoirApp.Domain.Entities.Choir", "Choir")
                        .WithMany("PlaylistTemplates")
                        .HasForeignKey("ChoirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Choir");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.PlaylistTemplateSection", b =>
                {
                    b.HasOne("ChoirApp.Domain.Entities.PlaylistTemplate", "PlaylistTemplate")
                        .WithMany("PlaylistTemplateSections")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaylistTemplate");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.PlaylistTemplateSong", b =>
                {
                    b.HasOne("ChoirApp.Domain.Entities.PlaylistTemplateSection", "PlaylistTemplateSection")
                        .WithMany("PlaylistTemplateSongs")
                        .HasForeignKey("TemplateSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaylistTemplateSection");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.SongTag", b =>
                {
                    b.HasOne("ChoirApp.Domain.Entities.MasterSong", "MasterSong")
                        .WithMany("SongTags")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChoirApp.Domain.Entities.Tag", "Tag")
                        .WithMany("SongTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterSong");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.UserChoir", b =>
                {
                    b.HasOne("ChoirApp.Domain.Entities.Choir", "Choir")
                        .WithMany("UserChoirs")
                        .HasForeignKey("ChoirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChoirApp.Domain.Entities.User", "User")
                        .WithMany("UserChoirs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Choir");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.Choir", b =>
                {
                    b.Navigation("ChoirSongVersions");

                    b.Navigation("PlaylistTemplates");

                    b.Navigation("Playlists");

                    b.Navigation("UserChoirs");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.MasterSong", b =>
                {
                    b.Navigation("ChoirSongVersions");

                    b.Navigation("SongTags");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.Playlist", b =>
                {
                    b.Navigation("PlaylistSections");

                    b.Navigation("PlaylistTags");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.PlaylistSection", b =>
                {
                    b.Navigation("PlaylistSongs");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.PlaylistTemplate", b =>
                {
                    b.Navigation("PlaylistTemplateSections");

                    b.Navigation("Playlists");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.PlaylistTemplateSection", b =>
                {
                    b.Navigation("PlaylistTemplateSongs");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.Tag", b =>
                {
                    b.Navigation("PlaylistTags");

                    b.Navigation("SongTags");
                });

            modelBuilder.Entity("ChoirApp.Domain.Entities.User", b =>
                {
                    b.Navigation("AdminOfChoirs");

                    b.Navigation("EditedSongs");

                    b.Navigation("UserChoirs");
                });
#pragma warning restore 612, 618
        }
    }
}
