import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useUser } from '../hooks/useUser';
import { createPlaylist, getPlaylistTemplatesByChoirId, getPlaylistTemplateById } from '../services/playlistService';
import { getSongsForChoir, searchSongs } from '../services/songService';
import { PlaylistTemplate, PlaylistSection, PlaylistSong } from '../types/playlist';
import { SongDto } from '../types/song';
import MovableSongItem from '../components/MovableSongItem';
import styles from './CreatePlaylistPage.module.scss';

const CreatePlaylistPage: React.FC = () => {
  const { user, token } = useUser();
  const navigate = useNavigate();
  const [title, setTitle] = useState('');
  const [isPublic, setIsPublic] = useState(false);
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
  const [templates, setTemplates] = useState<PlaylistTemplate[]>([]);
  const [selectedTemplate, setSelectedTemplate] = useState<PlaylistTemplate | null>(null);
  const [sections, setSections] = useState<PlaylistSection[]>([]);
  const [choirSongs, setChoirSongs] = useState<SongDto[]>([]);
  const [allSongs, setAllSongs] = useState<SongDto[]>([]);

  useEffect(() => {
    const fetchInitialData = async () => {
      if (user?.choirId && token) {
        try {
          const [fetchedTemplates, fetchedChoirSongs, fetchedAllSongs] = await Promise.all([
            getPlaylistTemplatesByChoirId(user.choirId, token),
            getSongsForChoir(user.choirId, token),
            searchSongs({}, token)
          ]);
          setTemplates(fetchedTemplates);
          setChoirSongs(fetchedChoirSongs);
          setAllSongs(fetchedAllSongs);
        } catch (error) {
          console.error(error);
        }
      }
    };

    fetchInitialData();
  }, [user, token]);

  const handleTemplateChange = async (templateId: string) => {
    if (templateId && token) {
      try {
        const template = await getPlaylistTemplateById(templateId, token);
        setSelectedTemplate(template);
        setSections(template.sections.map(s => ({...s, songs: []})));
      } catch (error) {
        console.error(error);
      }
    } else {
      setSelectedTemplate(null);
      setSections([]);
    }
  };

  const handleMoveSong = (song: PlaylistSong, fromSectionId: string, toSectionId: string) => {
    // Remove from original section
    const newSections = sections.map(s => 
      s.id === fromSectionId
        ? { ...s, songs: s.songs.filter(s => s.id !== song.id) }
        : s
    );

    // Add to target section
    const targetSectionIndex = newSections.findIndex(s => s.id === toSectionId);
    if (targetSectionIndex >= 0) {
      const targetSection = newSections[targetSectionIndex];
      const updatedSongs = [...targetSection.songs, { ...song, order: targetSection.songs.length }];
      newSections[targetSectionIndex] = { ...targetSection, songs: updatedSongs };
    }

    setSections(newSections);
  };

  const handleRemoveSongFromSection = (sectionId: string, songId: string) => {
    setSections(sections.map(s => 
      s.id === sectionId
        ? { ...s, songs: s.songs.filter(song => song.songId !== songId)}
        : s
    ));
  };

  const handleAddSongToSection = (sectionId: string, songId: string) => {
    const song = choirSongs.find(s => s.songId === songId);
    if (!song) return;

    const newSections = sections.map(section => {
      if (section.id === sectionId) {
        const newSong: PlaylistSong = {
          id: '', // This will be generated by the backend
          order: section.songs.length,
          songId: song.songId
        };
        return { ...section, songs: [...section.songs, newSong] };
      }
      return section;
    });
    setSections(newSections);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    // Only persist if there is at least one song in any section
    const hasSongs = sections.some(section => section.songs.length > 0);
    if (!hasSongs) {
      alert('Add at least one song before saving the playlist.');
      return;
    }
    if (user?.choirId && token) {
      try {
        await createPlaylist({ title, isPublic, choirId: user.choirId, date: new Date(date), sections, playlistTemplateId: selectedTemplate?.id }, token);
        navigate(`/choir/${user.choirId}/playlists`);
      } catch (error) {
        console.error(error);
      }
    }
  };


  return (
    <div className={styles.pageContainer}>
      <h1 className={styles.title}>New Playlist</h1>
      <form className={styles.form} onSubmit={handleSubmit}>
        <div className={styles.formGroup}>
          <label className={styles.label}>Title</label>
          <input
            className={styles.input}
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
        </div>
        <div className={styles.formGroup}>
          <label className={styles.label}>Date</label>
          <input
            className={styles.input}
            type="date"
            value={date}
            onChange={(e) => setDate(e.target.value)}
          />
        </div>
        <div className={styles.formGroup}>
          <label className={styles.label}>Template</label>
          <div className={styles.select}>
            <select
              value={selectedTemplate?.id || ''}
              onChange={(e) => handleTemplateChange(e.target.value)}
            >
              <option value="">No Template</option>
              {templates.map((template) => (
                <option key={template.id} value={template.id}>
                  {template.title}
                </option>
              ))}
            </select>
          </div>
        </div>
        <div className={styles.formGroup}>
          <label className={styles.checkbox}>
            <input
              type="checkbox"
              checked={isPublic}
              onChange={(e) => setIsPublic(e.target.checked)}
            />
            Public
          </label>
        </div>
        <div className={styles.formGroup}>
          <button className={styles.button} type="submit">
            Create
          </button>
        </div>
      </form>

      {selectedTemplate && (
        <div>
          <h2 className={styles.sectionTitle}>Sections</h2>
          {sections.map((section) => (
            <div key={section.id} className={styles.sectionBox}>
              <h3 className={styles.sectionTitle}>{section.title}</h3>
              <ul className={styles.songList}>
                {section.songs.map((song) => (
                  <MovableSongItem
                    key={song.songId}
                    song={song}
                    section={section}
                    sections={sections}
                    songs={[...choirSongs, ...allSongs]}
                    onMoveSong={handleMoveSong}
                    onRemoveSong={() => handleRemoveSongFromSection(section.id, song.songId)}
                  />
                ))}
              </ul>
              <div className={styles.addSongRow}>
                <div className={styles.select}>
                  <select onChange={(e) => handleAddSongToSection(section.id, e.target.value)}>
                    <option>Select a song</option>
                    {choirSongs.map(song => (
                      <option key={song.songId} value={song.songId}>{song.title}</option>
                    ))}
                  </select>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default CreatePlaylistPage;
