import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useUser } from '../hooks/useUser';
import { getPlaylistById as getPlaylist, updatePlaylist, getPlaylistTemplatesByChoirId } from '../services/playlistService';
import { getChoirSongsByChoirId } from '../services/choirSongService';
import { PlaylistTemplate, PlaylistSection, PlaylistSong } from '../types/playlist';
import { ChoirSongVersionDto } from '../types/choir';

const EditPlaylistPage: React.FC = () => {
  const { token } = useUser();
  const { playlistId } = useParams<{ playlistId: string }>();
  const navigate = useNavigate();
  const [title, setTitle] = useState('');
  const [isPublic, setIsPublic] = useState(false);
  const [loading, setLoading] = useState(true);
  const [templates, setTemplates] = useState<PlaylistTemplate[]>([]);
  const [selectedTemplate, setSelectedTemplate] = useState<PlaylistTemplate | null>(null);
  const [sections, setSections] = useState<PlaylistSection[]>([]);
  const [choirSongs, setChoirSongs] = useState<ChoirSongVersionDto[]>([]);

  useEffect(() => {
    const fetchInitialData = async () => {
      if (token && playlistId) {
        try {
          console.log("Fetching initial data...");
          const playlist = await getPlaylist(playlistId, token);
          const [fetchedTemplates, fetchedSongs] = await Promise.all([
            getPlaylistTemplatesByChoirId(playlist.choirId, token),
            getChoirSongsByChoirId(playlist.choirId, token)
          ]);
          
          console.log("Playlist data:", playlist);
          console.log("Templates data:", fetchedTemplates);
          
          setTitle(playlist.title || '');
          setIsPublic(playlist.isPublic);
          setSections(playlist.sections);
          setTemplates(fetchedTemplates);
          setChoirSongs(fetchedSongs);

          if (playlist.playlistTemplateId) {
            console.log("Playlist has templateId:", playlist.playlistTemplateId);
            const template = fetchedTemplates.find(t => t.id === playlist.playlistTemplateId);
            console.log("Found template:", template);
            setSelectedTemplate(template || null);
            if (playlist.sections.length === 0 && template) {
              console.log("Setting sections from template");
              setSections(template.sections.map(s => ({...s, songs: []})));
            }
          }

          setLoading(false);
        } catch (error) {
          console.error(error);
          setLoading(false);
        }
      }
    };

    fetchInitialData();
  }, [playlistId, token]);

  const handleAddSongToSection = (sectionId: string, choirSongVersionId: string) => {
    const song = choirSongs.find(s => s.choirSongId === choirSongVersionId);
    if (!song) return;

    const newSections = sections.map(section => {
      if (section.id === sectionId) {
        const newSong: PlaylistSong = {
          id: '', // This will be generated by the backend
          order: section.songs.length,
          choirSongVersionId: song.choirSongId,
          masterSongId: song.masterSongId
        };
        return { ...section, songs: [...section.songs, newSong] };
      }
      return section;
    });
    setSections(newSections);
  };

  const handleRemoveSongFromSection = (sectionId: string, songIndex: number) => {
    const newSections = sections.map(section => {
      if (section.id === sectionId) {
        const newSongs = [...section.songs];
        newSongs.splice(songIndex, 1);
        return { ...section, songs: newSongs };
      }
      return section;
    });
    setSections(newSections);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (token && playlistId) {
      try {
        await updatePlaylist(playlistId, { title, isPublic, sections, playlistTemplateId: selectedTemplate?.id }, token);
        navigate(`/playlists/${playlistId}`);
      } catch (error) {
        console.error(error);
      }
    }
  };

  if (loading) {
    return <div>Loading...</div>;
  }

  return (
    <div className="container">
      <h1 className="title">Edit Playlist</h1>
      <form onSubmit={handleSubmit}>
        <div className="field">
          <label className="label">Title</label>
          <div className="control">
            <input
              className="input"
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
            />
          </div>
        </div>
        <div className="field">
          <label className="checkbox">
            <input
              type="checkbox"
              checked={isPublic}
              onChange={(e) => setIsPublic(e.target.checked)}
            />
            Public
          </label>
        </div>
        <div className="field">
          <label className="label">Template</label>
          <div className="control">
            <div className="select">
              <select
                value={selectedTemplate?.id || ''}
                onChange={(e) => {
                  const template = templates.find(t => t.id === e.target.value);
                  setSelectedTemplate(template || null);
                  if (template) {
                    setSections(template.sections.map(s => ({...s, songs: []})));
                  } else {
                    setSections([]);
                  }
                }}
              >
                <option value="">No Template</option>
                {templates.map((template) => (
                  <option key={template.id} value={template.id}>
                    {template.title}
                  </option>
                ))}
              </select>
            </div>
          </div>
        </div>
        <div className="field">
          <div className="control">
            <button className="button is-primary" type="submit">
              Save Changes
            </button>
          </div>
        </div>
      </form>

      {selectedTemplate && (
        <div>
          <h2 className="title is-4 mt-5">Sections</h2>
          {sections.map((section) => (
            <div key={section.id} className="box">
              <h3 className="title is-5">{section.title}</h3>
              <ul>
                {section.songs.map((song, songIndex) => {
                  const songData = choirSongs.find(cs => cs.choirSongId === song.choirSongVersionId);
                  return (
                    <li key={songIndex}>
                      {songData?.masterSong?.title}
                      <button 
                        className="delete is-small ml-2" 
                        onClick={() => handleRemoveSongFromSection(section.id, songIndex)}
                      ></button>
                    </li>
                  );
                })}
              </ul>
              <div className="field has-addons mt-3">
                <div className="control">
                  <div className="select">
                    <select onChange={(e) => handleAddSongToSection(section.id, e.target.value)}>
                      <option>Select a song</option>
                      {choirSongs.map(song => (
                        <option key={song.choirSongId} value={song.choirSongId}>{song.masterSong?.title}</option>
                      ))}
                    </select>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default EditPlaylistPage;
